# Generated by Django 6.0.2 on 2026-03-25 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_level', models.SmallIntegerField(default=0, verbose_name='Learning Level')),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Next Review Date')),
                ('success_counter', models.SmallIntegerField(default=0, verbose_name='Success Counter')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'db_table': 'flashcards_word',
                'ordering': ['next_review_date'],
            },
        ),
    ]
