# Generated by Django 6.0.2 on 2026-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='success_counter',
            field=models.SmallIntegerField(default=0, verbose_name='Success Counter'),
        ),
    ]
