# Generated by Django 6.0.2 on 2026-03-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=150, verbose_name='Слово англійською')),
                ('translation', models.CharField(max_length=150, verbose_name='Переклад слова')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Приклад використання')),
                ('level', models.CharField(choices=[('A1', 'A1 (Початковий)'), ('A2', 'A2 (Базовий)'), ('B1', 'B1 (Середній)'), ('B2', 'B2 (Вище середнього)'), ('C1', 'C1 (Просунутий)'), ('C2', 'C2 (Вільне володіння)')], default='A1', max_length=2, verbose_name='Рівень')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='dictionary.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['english_word'],
            },
        ),
    ]
