# Generated by Django 6.0.2 on 2026-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Слово англійською'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Переклад слова'),
        ),
    ]
