# Generated by Django 6.0.2 on 2026-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_word_english_word_alter_word_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 (Початковий)'), ('A2', 'A2 (Базовий)'), ('B1', 'B1 (Середній)'), ('B2', 'B2 (Вище середнього)'), ('C1', 'C1 (Просунутий)'), ('C2', 'C2 (Вільне володіння)')], db_index=True, default='A1', max_length=2, verbose_name='Рівень'),
        ),
    ]
