# Generated by Django 6.0.5 on 2026-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_word_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Слово англійською'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Переклад слова'),
        ),
    ]
