# Generated by Django 6.0.2 on 2026-03-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Поточний стрік'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Остання активність'),
        ),
    ]
