upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name best-devs.studio www.best-devs.studio;

    # Для майбутніх оновлень сертифіката
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Автоматичне перенаправлення з http на https
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name best-devs.studio www.best-devs.studio;

    # Шляхи до твоїх нових сертифікатів
    ssl_certificate /etc/letsencrypt/live/best-devs.studio/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/best-devs.studio/privkey.pem;

    # Оптимізація SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    # Обробка статики (CSS, JS, Зображення)
    location /static/ {
        alias /app/staticfiles/;
    }
}
